[project]
name = "data-science-2"
version = "0.1.0"
description = ""
authors = [
    {name = "Ondrej Tybl",email = "ondra@tybl.cz"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "absl-py (==2.1.0)",
    "anyio (==4.8.0)",
    "appnope (==0.1.4)",
    "argon2-cffi (==23.1.0)",
    "argon2-cffi-bindings (==21.2.0)",
    "arrow (==1.3.0)",
    "asttokens (==3.0.0)",
    "async-lru (==2.0.4)",
    "attrs (==24.3.0)",
    "babel (==2.16.0)",
    "backports-tarfile (==1.2.0)",
    "beautifulsoup4 (==4.12.3)",
    "bleach (==6.2.0)",
    "build (==1.2.2.post1)",
    "cachecontrol (==0.14.2)",
    "certifi (==2024.12.14)",
    "cffi (==1.17.1)",
    "chaid (==5.4.1)",
    "charset-normalizer (==3.4.1)",
    "cleo (==2.1.0)",
    "cloudpickle (==3.1.1)",
    "comm (==0.2.2)",
    "contourpy (==1.3.1)",
    "crashtest (==0.4.1)",
    "cycler (==0.12.1)",
    "cython (==3.0.11)",
    "datetime (==5.4)",
    "debugpy (==1.8.12)",
    "decorator (==5.1.1)",
    "defusedxml (==0.7.1)",
    "distlib (==0.3.9)",
    "dulwich (==0.22.7)",
    "exceptiongroup (==1.2.2)",
    "executing (==2.1.0)",
    "fastjsonschema (==2.21.1)",
    "filelock (==3.16.1)",
    "fonttools (==4.55.3)",
    "fqdn (==1.5.1)",
    "fsspec (==2024.12.0)",
    "future (==1.0.0)",
    "graphviz (==0.16)",
    "h11 (==0.14.0)",
    "h5py (==3.12.1)",
    "httpcore (==1.0.7)",
    "httpx (==0.28.1)",
    "hyperopt (==0.2.7)",
    "idna (==3.10)",
    "importlib-metadata (==8.5.0)",
    "installer (==0.7.0)",
    "ipykernel (==6.29.5)",
    "ipython (==8.31.0)",
    "ipywidgets (==8.1.5)",
    "isoduration (==20.11.0)",
    "jaraco-classes (==3.4.0)",
    "jaraco-context (==6.0.1)",
    "jaraco-functools (==4.1.0)",
    "jedi (==0.19.2)",
    "jinja2 (==3.1.5)",
    "joblib (==1.4.2)",
    "json5 (==0.10.0)",
    "jsonpointer (==3.0.0)",
    "jsonschema (==4.23.0)",
    "jsonschema-specifications (==2024.10.1)",
    "jupyter (==1.1.1)",
    "jupyter-console (==6.6.3)",
    "jupyter-events (==0.11.0)",
    "jupyter-lsp (==2.2.5)",
    "jupyter-client (==8.6.3)",
    "jupyter-core (==5.7.2)",
    "jupyter-server (==2.15.0)",
    "jupyter-server-terminals (==0.5.3)",
    "jupyterlab (==4.3.4)",
    "jupyterlab-pygments (==0.3.0)",
    "jupyterlab-server (==2.27.3)",
    "jupyterlab-widgets (==3.0.13)",
    "keras (==3.8.0)",
    "keyring (==25.6.0)",
    "kiwisolver (==1.4.8)",
    "markdown-it-py (==3.0.0)",
    "markupsafe (==3.0.2)",
    "matplotlib (==3.8.2)",
    "matplotlib-inline (==0.1.7)",
    "mdurl (==0.1.2)",
    "mistune (==3.1.0)",
    "ml-dtypes (==0.4.0)",
    "more-itertools (==10.6.0)",
    "mpmath (==1.3.0)",
    "msgpack (==1.1.0)",
    "mtcnn (==0.1.1)",
    "namex (==0.0.8)",
    "nbclient (==0.10.2)",
    "nbconvert (==7.16.5)",
    "nbformat (==5.10.4)",
    "nest-asyncio (==1.6.0)",
    "networkx (==3.4.2)",
    "notebook (==7.3.2)",
    "notebook-shim (==0.2.4)",
    "numpy (==1.26.4)",
    "opencv-python (==4.11.0.86)",
    "optree (==0.14.0)",
    "overrides (==7.7.0)",
    "packaging (==24.2)",
    "pandas (==2.2.3)",
    "pandocfilters (==1.5.1)",
    "parso (==0.8.4)",
    "pexpect (==4.9.0)",
    "pillow (==10.2.0)",
    "pkginfo (==1.12.0)",
    "platformdirs (==4.3.6)",
    "poetry (==2.0.1)",
    "poetry-core (==2.0.1)",
    "prometheus-client (==0.21.1)",
    "prompt-toolkit (==3.0.50)",
    "psutil (==6.1.1)",
    "ptyprocess (==0.7.0)",
    "pure-eval (==0.2.3)",
    "py4j (==0.10.9.9)",
    "pycparser (==2.22)",
    "pydot (==1.4.2)",
    "pygments (==2.19.1)",
    "pyparsing (==3.2.1)",
    "pyproject-hooks (==1.2.0)",
    "python-dateutil (==2.9.0.post0)",
    "python-json-logger (==3.2.1)",
    "pytz (==2024.2)",
    "pyyaml (==6.0.2)",
    "pyzmq (==26.2.0)",
    "rapidfuzz (==3.11.0)",
    "referencing (==0.36.1)",
    "requests (==2.32.3)",
    "requests-toolbelt (==1.0.0)",
    "rfc3339-validator (==0.1.4)",
    "rfc3986-validator (==0.1.1)",
    "rich (==13.9.4)",
    "rpds-py (==0.22.3)",
    "scikit-learn (==1.4.0)",
    "scipy (==1.12.0)",
    "seaborn (==0.13.1)",
    "send2trash (==1.8.3)",
    "shellingham (==1.5.4)",
    "six (==1.17.0)",
    "sniffio (==1.3.1)",
    "soupsieve (==2.6)",
    "stack-data (==0.6.3)",
    "sympy (==1.13.1)",
    "terminado (==0.18.1)",
    "threadpoolctl (==3.5.0)",
    "tinycss2 (==1.4.0)",
    "tomli (==2.2.1)",
    "tomlkit (==0.13.2)",
    "torch (==2.5.1)",
    "torchaudio (==2.5.1)",
    "torchvision (==0.20.1)",
    "tornado (==6.4.2)",
    "tqdm (==4.67.1)",
    "traitlets (==5.14.3)",
    "treelib (==1.7.0)",
    "trove-classifiers (==2025.1.15.22)",
    "types-python-dateutil (==2.9.0.20241206)",
    "typing-extensions (==4.12.2)",
    "tzdata (==2024.2)",
    "uri-template (==1.3.0)",
    "urllib3 (==2.3.0)",
    "virtualenv (==20.29.1)",
    "wcwidth (==0.2.13)",
    "webcolors (==24.11.1)",
    "webencodings (==0.5.1)",
    "websocket-client (==1.8.0)",
    "widgetsnbextension (==4.0.13)",
    "xattr (==1.1.4)",
    "xgboost (==2.0.3)",
    "zipp (==3.21.0)",
    "zope-interface (==7.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
